---
title: "**Rapport sur l'analyse de l'évolution de l'état biologique de l'élément
  déclassant, pour les stations suivies en Normandie.**"
author: "`r params$author`"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    highlight: pygments
    theme: default
    toc: false
    css: css/ofb_theme_html.css
params:
  auteur: Julia Mourgues
  annee_debut: 2007
  annee_fin: 2024
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)
```

```{r, echo = FALSE}
htmltools::img(src = knitr::image_uri(here::here("Script/css", "logo_OFB_v2.png")),
               alt = 'logo',
               style = 'position:absolute; top:0; right:0; padding:10px; width:180px;')
```


> ⚠ **Préambule** :<br>
> 
> Les données couvrent la **période de `r params$annee_debut` à `r params$annee_fin`** (*paramètres de filtres pour la génération de cette fiche*). <br>
<br>
<br>

```{r message=FALSE, warning=FALSE, echo = FALSE}
library(tidyverse)
library(sf)
library(ggtext)
library(gt)
library(ggh4x)
library(colorspace)
library(here)
library(glue)
library(ggrepel)
library(ggiraph)
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
data_element_declassant <- readRDS(here("Data/clean_data", "table_element_declassant.rds"))

mes_stations <- readRDS(here("Data/clean_data", "liste_stations_retenues.rds"))
```


```{r message=FALSE, warning=FALSE, echo = FALSE}
source(here::here("R", "fun_classe_ecologique.R"))
source(here::here("R", "fun_graph_diagramme_alluvial.R"))
```


# 1. Présentation du nombre de stations par classe d'état biologique et par année
<br>

```{r}
stat_etat_annee <- data_element_declassant %>%
  filter(reseaux != "RRP" | annee >= 2013) %>% 
  group_by(reseaux, annee) %>% 
  summarise(n_tb = sum(etat_biologique=="Très bon", na.rm = TRUE),
            n_bon = sum(etat_biologique=="Bon", na.rm = TRUE),
            n_moyen = sum(etat_biologique=="Moyen", na.rm = TRUE),
            n_mediocre = sum(etat_biologique=="Médiocre", na.rm = TRUE),
            n_mauvais = sum(etat_biologique=="Mauvais", na.rm = TRUE),
            n_total = n_distinct(code_station),
            .groups ="drop")
```

```{r out.width="80%"}
table_etat_annee <- stat_etat_annee %>% 
  mutate(reseaux=paste("Réseau ", reseaux)) %>% 
  group_by(reseaux) %>% 
  gt() %>% 
  cols_hide(columns = c(reseaux)) %>% 
  gt::tab_header(
      title = md("**Nombre de stations par classe d'état écologique.**"),
      subtitle = "Pour chaque année, la classe d'état biologique considérée est celle de l'élément déclassant.") %>% 
  gt::cols_label(
      annee="Année",
      n_tb = "Très bon",
      n_bon = "Bon",
      n_moyen= "Moyen",
      n_mediocre= "Médiocre",
      n_mauvais= "Mauvais",
      n_total="Nombre de stations total"
    ) %>%
  opt_row_striping() %>% 
  tab_style(
    style = list(
      cell_text(weight = "bold", size = px(13)),
      cell_fill(color = "#f7f7f7")
    ),
    locations = cells_row_groups()
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold", size=px(13)), 
    locations = cells_column_labels(everything())
  ) %>% 
  tab_style(
    style = cell_text( size=px(12)),  
    locations = cells_body()) %>% 
  tab_style(
    style = cell_text(color = "#2b83ba",weight = "bold"),
    locations = cells_body(columns = n_tb)
  )%>% 
  tab_style(
    style = cell_text(color = "#90EE90",weight = "bold"),
    locations = cells_body(columns = n_bon)
  )%>% 
  tab_style(
    style = cell_text(color = "#F2F200",weight = "bold"),
    locations = cells_body(columns = n_moyen)
  )%>% 
  tab_style(
    style = cell_text(color = "#FFA500",weight = "bold"),
    locations = cells_body(columns = n_mediocre)
  )%>% 
  tab_style(
    style = cell_text(color = "#FF0000",weight = "bold"),
    locations = cells_body(columns = n_mauvais)
  )



table_etat_annee
```
<br>
<br>
<br>


# 2. Visualisation des flux de station entre les classes d'état biologique au cours du temps
<br>

```{r}
table_element_declassant_RRP <- data_element_declassant %>% 
  filter(reseaux=="RRP",
         annee >=2013) %>% 
  arrange(code_station, annee)

data_RRP_large <- table_element_declassant_RRP %>% 
  pivot_wider(
    id_cols = code_station,
    names_from = annee, 
    values_from = etat_biologique)

year_cols <- setdiff(names(data_RRP_large), c("code_station"))
    
years_num <- sort(suppressWarnings(as.numeric(year_cols)))
years_kept <- as.character(years_num)
    
    
#Passage au format lodes (ggalluvial)
data_lodes_RRP <- ggalluvial::to_lodes_form(
  data_RRP_large,
  key = "annee",
  axes = years_kept,
  value = "etat"
)
    
data_lodes_RRP$etat <- forcats::fct_explicit_na(
  data_lodes_RRP$etat,
  na_level = "Non évalué"
)
    
data_lodes_RRP$annee <- base::factor(data_lodes_RRP$annee, 
                                 levels = years_kept)
    
data_lodes_RRP$etat <- factor(
  data_lodes_RRP$etat,
  levels = c("Très bon", "Bon", "Moyen", "Médiocre","Mauvais" , "Non évalué"),
  ordered = TRUE
)
    
#Définir les couleurs associées aux niveaux
couleurs <- c("#FFFFFF","#FF0000", "#FFA500", "#FFFF00", "#90EE90", "#2b83ba")
classes   = c("Non évalué","Mauvais", "Médiocre", "Moyen", "Bon", "Très bon")
palette_etat <- stats::setNames(couleurs, classes)
    
    
plot_declassant_RRP <- ggplot2::ggplot(
  data_lodes_RRP,
  ggplot2::aes(
    x        = annee,
    stratum  = etat,
    alluvium = code_station,
    y        = 1,             # chaque station contribue de façon égale
    fill     = etat
  )
) +
  ggalluvial::geom_flow(ggplot2::aes(alpha = etat),color="darkgrey") +
  ggalluvial::geom_stratum() +
  ggplot2::scale_fill_manual(values = palette_etat, drop = TRUE) +
  ggplot2::scale_alpha_manual(
    values = c(
      "Très bon"    = 0.6,
      "Bon"         = 0.6,
      "Moyen"       = 0.6,
      "Médiocre"    = 0.6,
      "Mauvais"     = 0.6,
      "Non évalué"  = 0.15   # très léger
    ),
    guide = "none"
  ) +
  ggplot2::theme_bw() +
  ggplot2::labs(
    title    = "Diagramme alluvial – évolution du nombre de stations par classe d’état biologique",
    subtitle = "Réseau RRP, les classes d'état biologique sont celles retenues pour la DCE.",
    x        = "Années",
    y        = "Nombre de stations",
    fill     = "État biologique"
  ) +
  ggplot2::theme(
    plot.title   = ggtext::element_textbox_simple(size = 14, face = "bold", margin = ggplot2::margin(b = 5)),
    plot.subtitle= ggtext::element_textbox_simple(size = 15, margin = ggplot2::margin(b = 10)),
    axis.title   = ggplot2::element_text(size = 14),
    axis.text = ggplot2::element_text(size = 13),
    legend.title = ggplot2::element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.position = "top",
    legend.text = ggplot2::element_text(size = 13)
  )+
  ggplot2::guides(
    fill  = guide_legend(order = 1, ncol = 6))
```

```{r}
table_element_declassant_RCS <- data_element_declassant %>% 
  filter(reseaux=="RCS") %>% 
  arrange(code_station, annee)

data_RCS_large <- table_element_declassant_RCS %>% 
  pivot_wider(
    id_cols = code_station,
    names_from = annee, 
    values_from = etat_biologique)

year_cols <- setdiff(names(data_RCS_large), c("code_station"))
    
years_num <- sort(suppressWarnings(as.numeric(year_cols)))
years_kept <- as.character(years_num)
    
    
#Passage au format lodes (ggalluvial)
data_lodes_RCS <- ggalluvial::to_lodes_form(
  data_RCS_large,
  key = "annee",
  axes = years_kept,
  value = "etat"
)
    
data_lodes_RCS$etat <- forcats::fct_explicit_na(
  data_lodes_RCS$etat,
  na_level = "Non évalué"
)
    
data_lodes_RCS$annee <- base::factor(data_lodes_RCS$annee, 
                                 levels = years_kept)
    
data_lodes_RCS$etat <- factor(
  data_lodes_RCS$etat,
  levels = c("Très bon", "Bon", "Moyen", "Médiocre","Mauvais" , "Non évalué"),
  ordered = TRUE
)
    
#Définir les couleurs associées aux niveaux
couleurs <- c("#FFFFFF","#FF0000", "#FFA500", "#FFFF00", "#90EE90", "#2b83ba")
classes   = c("Non évalué","Mauvais", "Médiocre", "Moyen", "Bon", "Très bon")
palette_etat <- stats::setNames(couleurs, classes)
    
plot_declassant_RCS <- ggplot2::ggplot(
  data_lodes_RCS,
  ggplot2::aes(
    x        = annee,
    stratum  = etat,
    alluvium = code_station,
    y        = 1,             # chaque station contribue de façon égale
    fill     = etat
  )
) +
  ggalluvial::geom_flow(ggplot2::aes(alpha = etat),color="darkgrey") +
  ggalluvial::geom_stratum() +
  ggplot2::scale_fill_manual(values = palette_etat, drop = TRUE) +
  ggplot2::scale_alpha_manual(
    values = c(
      "Très bon"    = 0.6,
      "Bon"         = 0.6,
      "Moyen"       = 0.6,
      "Médiocre"    = 0.6,
      "Mauvais"     = 0.6,
      "Non évalué"  = 0.15   # très léger
    ),
    guide = "none"
  ) +
  ggplot2::theme_bw() +
  ggplot2::labs(
    title    = "Diagramme alluvial – évolution du nombre de stations par classe d’état biologique",
    subtitle = "Réseau RCS, les classes d'état biologique sont celles retenues pour la DCE.",
    x        = "Années",
    y        = "Nombre de stations",
    fill     = "État biologique"
  ) +
  ggplot2::theme(
    plot.title   = ggtext::element_textbox_simple(size = 14, face = "bold", margin = ggplot2::margin(b = 5)),
    plot.subtitle= ggtext::element_textbox_simple(size = 15, margin = ggplot2::margin(b = 10)),
    axis.title   = ggplot2::element_text(size = 14),
    axis.text = ggplot2::element_text(size = 13),
    legend.title = ggplot2::element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    legend.title.position = "top",
    legend.text = ggplot2::element_text(size = 13)
  )+
  ggplot2::guides(
    fill  = guide_legend(order = 1, ncol = 6))

```


```{r fig.width=13, fig.height=12, out.width="90%", fig.align='center'}
library(patchwork)
plot_declassant_RRP_clean <- plot_declassant_RRP + labs(title = NULL)
plot_declassant_RCS_clean <- plot_declassant_RCS + labs(title = NULL)

plot_combine <- (plot_declassant_RRP_clean / plot_declassant_RCS_clean) +
  plot_annotation(title = "Diagrammes alluviaux – évolution du nombre de stations par classe d’état biologique",
    x= "Années",
    y = "Nombre de stations",
    theme = theme(
      plot.title = element_text(size = 16, face = "bold"),
      plot.subtitle = element_text(size = 15),
      axis.title   = ggplot2::element_text(size = 14)
    ))+
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")

plot_combine
```
<br>
<br>
<br>
