---
title: "Graph alluviaux DCE"
author: "Julia"
date: "2026-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Installation

## Chargement des packages

```{r}
library(tidyverse)
library(here)
library(sf)
library(MASS) #réaliser le modèle logistique ordinal
library(gtsummary)
library(brant) #réaliser le test d'égalité des pentes
library(ordinal)
library(ggtext)
library(pbapply) #afficher barre de chargement
library(broom.mixed)
library(ggalluvial)
```

## Chargement des données

```{r}
BDD_indices_DCE <- readRDS(here("Data/clean_data", "BDD_3_cycle_indices.rds"))
BDD_indices <- readRDS(here("Data/clean_data", "BDD_indices.rds"))
mes_stations <- readRDS(here("Data/clean_data", "liste_stations_retenues.rds"))
```

## Chargement des fonctions
```{r}
source(here::here("R","fun_graph_diagramme_alluvial.R"))
source(here::here("R","fun_classe_ecologique.R"))
```

# Création des tables

On calcule la moyenne des résultats pour chaque indice par station et par cycle DCE
Il faut garder les stations pour lesquelles on a des données pour les 3 cycles DCE.
```{r}
BDD_indices_mediane <- BDD_indices %>%
  st_drop_geometry() %>% 
  filter(code_station %in% mes_stations) %>% 
  group_by(
    code_indice,
    libelle_indice,
    code_station,
    libelle_station,
    reseaux,
    Typologie,
    cycle_DCE
  ) %>%
  mutate(cycle_DCE = as.factor(cycle_DCE)) %>% #nécessaire pour effectuer l'ANOVA
  summarise(mediane_eqr = round(median(resultat_eqr),2), .groups = "drop") %>% 
  attribuer_classe_eco(
    table_seuils = valeurs_seuils,
    var_eqr = "mediane_eqr",
    var_temp = "cycle_DCE"
    ) %>%  #attribuer la classe d'état écologique à la mediane
  rename(libelle_classe=classe) %>% 
  dplyr:: select(-seuil_bas, -seuil_haut, -couleur)
```


On va générer les diagramme pour différentes combinaisons de réseaux
```{r}
diag_alluvial_DCE(
  data = BDD_indices_mediane,
  liste_reseaux = c("RRP"),
  output_dir = "../Output/4_Proportions_classes_eco/03_Sankey/Cycle_DCE"
)

diag_alluvial_DCE(
  data = BDD_indices_mediane,
  liste_reseaux = c("RCS"),
  output_dir = "../Output/4_Proportions_classes_eco/03_Sankey/Cycle_DCE"
)
```

